<?php
/**
 * @author Edgar J. Gómez
 * @copyright Copyright (c) 2017 Edgargomez (http://www.edgargomez.es)
 * @package Edgargomez_CookieMsg
 */
?>
<?php
$helper = $this->helper('Edgargomez\CookieMsg\Helper\Data');
if ($helper->getConfig('edgargomez_cookiemsg/general/enable')) {

	$lifeTime        = $helper->getConfig('edgargomez_cookiemsg/general/lifetime');
	$mesgPosition    = $helper->getConfig('edgargomez_cookiemsg/general/msg_position');
	$privacyUrl      = $helper->getConfig('edgargomez_cookiemsg/general/privacy_url');
	$privacyLinkText = $helper->getConfig('edgargomez_cookiemsg/general/privacy_link_text');
	$privacyTitle    = $helper->getConfig('edgargomez_cookiemsg/general/privacy_title');
	$message         = $helper->getConfig('edgargomez_cookiemsg/general/privacy_message');
    $showAccept      = $helper->getConfig('edgargomez_cookiemsg/general/showaccept');
    $acceptText      = $helper->getConfig('edgargomez_cookiemsg/general/depends_accepttext');
    $devMode         = $helper->getConfig('edgargomez_cookiemsg/developer/devMode');
	$custom_css      = $helper->getConfig('edgargomez_cookiemsg/developer/css_styling'); 

?>
    
    <div id="on-cm-wrap">
        <span><?php echo $message; ?><a href="<?php echo $privacyUrl; ?>" id="on-cm-ll"><?php echo $privacyLinkText; ?></a>
        <br/>
        <?php if ($showAccept): ?>
            <a href="#" id="on-cm-hide"><?php echo $acceptText ?></a></span>
        <?php endif; ?>
    </div>
    <script type="text/javascript">
        requirejs(['jquery','jquery.cookie'],function(jQuery){
            (function($) {
                // Show cookie bar
                if ($.cookie('edgargomez_cookiemsg') != "true") {
                    $('#on-cm-wrap').show();
                }
                // Handle hide button
                $('#on-cm-hide').click(function(event) {
                    event.preventDefault();
                    $('#on-cm-wrap').hide();
                    // SET COOKIE
                    $.cookie('edgargomez_cookiemsg', "true", { expires: <?php echo $lifeTime; ?>, path: '/' });
                })
            })(jQuery);
        });
    </script>
    <?php if($devMode): ?> 
        <style type="text/css">
            #on-cm-wrap {display: block !important;}
        </style> 
    <?php endif; ?>
    <?php if (strlen($custom_css) > 0) { ?>
    <style type="text/css">
        <?php echo $custom_css; ?>
    </style>
    <?php } ?>
<?php

} ?>